### PR TITLE
Preserve timestamp milliseconds when serializing WireMessage (#1)

### PR DESCRIPTION
**Pull request by semyon2105**
Hi!

This change makes it so milliseconds of chrono::DateTime are preserved when serializing it into a GELF timestamp.

### CODE REVIEW

**Comment by bzikarsky** [comment]
I'm not sure, but serializing the timestamp should give an ISO8601 (or similar) timestamp. Adding ".13245" for millisecond precision, shouldn't work. We probably should also add a test for the general format...

**Comment by semyon2105** [comment]
It's stated in [GELF spec](http://docs.graylog.org/en/2.4/pages/gelf.html#gelf-payload-specification) that it supports timestamps with a decimal point for milliseconds.
I may add a test later this week.

**Comment by bzikarsky** [comment]
Oh, I was mistaken. I thought GELF used a timestamp like 2018-11-12T11:30:18.12345+00:02. Sorry. :smile:

Do you want me to merge right away or do you want to add a test first?

**Comment by semyon2105** [comment]
It's up to you. I can add a test as a separate PR.

**Comment by bzikarsky** [comment]
Let's merge it with the test. :)

**Comment by bzikarsky** [comment]
Thanks! :+1:

**Pull request merged**
