### PR TITLE
Performance improvements on compression

### PR DESCRIPTION
**Pull request by dangerousplay**
Hi, i have made some changes are related to compression performance and overall upgrade to Rust 2018 edition. I have integrated some benchmark and other unit tests.

Related issue #17

Suggestions are appreciated.

### CODE REVIEW

**Comment by bzikarsky** [comment]
Oh wow! That looks awesome! I'll try to give it a thorough look tonight and tag it ASAP.

Already a bug thanks :)

**Comment by dangerousplay** [comment]
Take your time, it's my first project using Rust. There are points to subject of change, no problem.

**Comment by bzikarsky** [comment]
I just looked through it, I like it. Sorry for being late. :|

The tests seem to have failed because of crates.io, I just restarted them. Let's see. If they turn green I'm fine with merging/tagging this. :-)

**Comment by bzikarsky** [comment]
```
warning: unused import: `TimeZone`
 --> src/message/mod.rs:3:29
  |
3 | use chrono::{DateTime, Utc, TimeZone, NaiveDateTime};
  |                             ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

This probably can be removed

**Comment by dangerousplay** [comment]
> ```
> warning: unused import: `TimeZone`
>  --> src/message/mod.rs:3:29
>   |
> 3 | use chrono::{DateTime, Utc, TimeZone, NaiveDateTime};
>   |                             ^^^^^^^^
>   |
>   = note: `#[warn(unused_imports)]` on by default
> ```
> 
> This probably can be removed

Solved.

**Comment by bzikarsky** [comment]
I merged, I'll package this up and will publish it to crates.io. Thanks again for this major contribution!

**Pull request merged**
